runtime: python39

entrypoint: gunicorn -b :$PORT crmsystem.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "crmsystem.settings"
  GSPREAD_CLIENT_SECRET_FILE: "deannandi.co.ke/gsheets/aggerman-sheets-f393f9ef2934.json"  # Update this with the path to your GCP service account credentials file
  SECRET_KEY: "django-insecure-*^cv^_cmrvobr!yfo^n3o7g46t+*!7vk)*-1gww364b57g@_=t"  # Replace with your actual secret key
  DEBUG: "False"  # Set to "False" for production
  ALLOWED_HOSTS: "crm-system.germaninstitute.co.ke"  # Replace with your actual domain or IP

handlers:
- url: /static
  static_dir: static/
- url: /media
  static_dir: media/
- url: /.*
  script: auto
