# Generated by Django 4.2.7 on 2023-12-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course_class_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_intake',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
