# Generated by Django 4.2.7 on 2024-01-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='reason_for_absence',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_of_class',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crmpage.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absent',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Yes', 'Yes'), ('No', 'No')], default='Pending', max_length=50, null=True),
        ),
    ]
