# Generated by Django 4.2.7 on 2023-12-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0002_candidate_course_class_no_candidate_course_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='course_class_no',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='course_intake',
            field=models.CharField(choices=[('None', 'None'), ('Class A1 (DEC-AUG 2023/2024)', 'Class A1 (DEC-AUG 2023/2024)')], max_length=255, null=True),
        ),
    ]
