# Generated by Django 4.2.7 on 2024-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0002_remove_attendance_date_remove_attendance_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
