# Generated by Django 4.2.7 on 2023-12-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0005_candidate_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Qualification',
            field=models.CharField(choices=[('Kenya Registerd Community Health Nurse (KRCHN)', 'Kenya Registerd Community Health Nurse (KRCHN)'), ('Kenya Enrolled Community Health Nurse (KECHN)', 'Kenya Enrolled Community Health Nurse (KECHN)'), ('B.Sc Nursing (BSN)', 'B.Sc Nursing (BSN)'), ('Newly Graduated Nursing Student (diploma/BSN)', 'Newly Graduated Nursing Student (diploma/BSN)'), ('Nurse Aid', 'Nurse Aid'), ('Clinical Officer', 'Clinical Officer'), ('Other Qualification', 'Other Qualification')], max_length=255, null=True),
        ),
    ]
