# Generated by Django 4.2.7 on 2023-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0007_alter_candidate_course_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sheet_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
