# Generated by Django 4.2.7 on 2024-01-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0008_alter_attendance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(max_length=12, unique=True)),
                ('date_of_payment', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
