# Generated by Django 4.2.7 on 2023-12-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0009_sheet1application_sheet2application'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet1application',
            name='sheet_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
