# Generated by Django 4.2.7 on 2024-01-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0009_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=12, unique=True)),
                ('date_of_payment', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmpage.candidate')),
            ],
        ),
    ]
