# Generated by Django 4.2.7 on 2023-12-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0010_sheet1application_sheet_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sheet1Application',
        ),
    ]
