# Generated by Django 4.2.7 on 2023-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0011_delete_sheet1application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sheet2Application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sheet_name',
        ),
    ]
