# Generated by Django 4.2.7 on 2024-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0012_eldoret_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldoret_applicant',
            name='Identification_Card_Image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_ID_photos/'),
        ),
    ]
