# Generated by Django 4.2.7 on 2024-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0013_eldoret_applicant_identification_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Identification_Card_Image',
            field=models.ImageField(upload_to='applicant_ID_photos/'),
        ),
    ]
