# Generated by Django 4.2.7 on 2023-12-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0013_sheet2application_application_sheet2application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet2application',
            name='license_number',
        ),
    ]
