# Generated by Django 4.2.7 on 2024-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0014_alter_eldoret_applicant_identification_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='absent_reason',
            field=models.CharField(blank=True, choices=[('TL', 'Too Late'), ('AE', 'Absent with Excuse'), ('AWE', 'Absent without Excuse')], max_length=50),
        ),
    ]
