# Generated by Django 4.2.7 on 2023-12-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0015_alter_candidate_college_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Course_Location',
            field=models.CharField(choices=[('Nairobi-CBD', 'Nairobi-CBD'), ('Nairobi-Daystar', 'Nairobi-Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret')], max_length=50, null=True),
        ),
    ]
