# Generated by Django 4.2.7 on 2024-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0015_alter_classattendance_absent_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldoret_applicant',
            name='Number_Of_Children',
            field=models.IntegerField(blank=True, max_length=512, null=True),
        ),
    ]
