# Generated by Django 4.2.7 on 2024-01-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0016_eldoret_applicant_number_of_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eldoret_applicant',
            old_name='Spouse_Name',
            new_name='Spouse_Qualification',
        ),
    ]
