# Generated by Django 4.2.7 on 2024-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0017_rename_spouse_name_eldoret_applicant_spouse_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldoret_applicant',
            name='Grade',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
