# Generated by Django 4.2.7 on 2024-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0017_alter_application_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Invoice_Number', models.CharField(max_length=50)),
                ('Date_of_Payment', models.DateField()),
            ],
        ),
    ]
