# Generated by Django 4.2.7 on 2024-01-30 13:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0018_eldoret_applicant_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Course_Location',
            field=models.CharField(blank=True, choices=[('Nairobi-CBD', 'Nairobi-CBD'), ('Nairobi-Daystar', 'Nairobi-Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True),
        ),
    ]
