# Generated by Django 4.2.7 on 2024-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0018_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='AmountPaid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
