# Generated by Django 4.2.7 on 2024-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0019_alter_eldoret_applicant_course_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Time',
            field=models.CharField(choices=[('None', 'None'), ('morning (around 8:30 - 12:30)', 'morning (around 8:30 - 12:30)'), ('afternoon (around 13:00 - 17:00)', 'afternoon (around 13:00 - 17:00)'), ('evening (around 17:30 - 21:00)', 'evening (around 17:30 - 21:00)')], default='None', max_length=50, null=True),
        ),
    ]
