# Generated by Django 4.2.7 on 2024-01-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0019_invoice_amountpaid_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='signed_contracts/')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='crmpage.candidate')),
            ],
        ),
    ]
