# Generated by Django 4.2.7 on 2024-01-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0020_contract'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Teacher',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crmpage.candidate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='course_intake',
            field=models.CharField(choices=[('Class (DEC-AUG 2023/2024 Semester)', 'Class (DEC-AUG 2023/2024 Semester)'), ('Class (JAN-SEPT 2024 Semester)', 'Class (JAN-SEPT 2024 Semester)')], max_length=255, null=True),
        ),
    ]
