# Generated by Django 4.2.7 on 2024-01-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0020_alter_eldoret_applicant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='absent_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Level_Of_German',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='child_sex',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='fluency_in_language',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('English Beginner', 'English Beginner'), ('English Intermediate', 'English Intermediate'), ('English Advanced', 'English Advanced')], default='None', max_length=50, null=True),
        ),
    ]
