# Generated by Django 4.2.7 on 2024-01-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0021_rename_school_teacher_remove_attendance_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crmpage.teacher'),
            preserve_default=False,
        ),
    ]
