# Generated by Django 4.2.7 on 2024-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0021_alter_classattendance_absent_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='absent_reason',
            field=models.CharField(blank=True, choices=[('Too Late', 'Too Late'), ('Absent with Excuse', 'Absent with Excuse'), ('Absent without Excuse', 'Absent without Excuse')], max_length=255, null=True),
        ),
    ]
