# Generated by Django 4.2.7 on 2024-01-11 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0022_attendance_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
