# Generated by Django 4.2.7 on 2024-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0022_alter_classattendance_absent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
