# Generated by Django 4.2.7 on 2024-01-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0023_alter_classattendance_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='present',
            field=models.BooleanField(),
        ),
    ]
