# Generated by Django 4.2.7 on 2024-02-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0024_alter_classattendance_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_to_pay', models.IntegerField()),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(max_length=12)),
            ],
        ),
    ]
