# Generated by Django 4.2.7 on 2024-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0025_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.IntegerField()),
                ('date', models.DateField()),
                ('discount_number', models.CharField(max_length=12)),
            ],
        ),
    ]
