# Generated by Django 4.2.7 on 2024-01-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0027_alter_candidate_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='course_intake',
            field=models.CharField(blank=True, choices=[('Class (DEC-AUG 2023/2024 Semester)', 'Class (DEC-AUG 2023/2024 Semester)'), ('Class (JAN-SEPT 2024 Semester)', 'Class (JAN-SEPT 2024 Semester)')], max_length=255, null=True),
        ),
    ]
