# Generated by Django 4.2.7 on 2024-02-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0028_alter_feestructure_fee_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmpage.candidate'),
        ),
    ]
