# Generated by Django 4.2.7 on 2024-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0028_alter_candidate_course_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='College_Degree_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='College_Degree_secondary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='College_Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='College_Year_Secondary',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='College_Year_tertiary',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='College_tertiary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='High_School_Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='High_School_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_Year_end',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_secondary_Year_end',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_secondary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_tertiary_Year_end',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Institution_tertiary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_Year_secondary',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_Year_tertiary',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_secondary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='University_tertiary_Year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
