# Generated by Django 4.2.7 on 2024-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0029_alter_candidate_college_degree_year_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_of_class',
            field=models.DateField(blank=True, null=True),
        ),
    ]
