# Generated by Django 4.2.7 on 2024-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0029_feestructure_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Level_Of_German',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], default='None', max_length=50, null=True),
        ),
    ]
