# Generated by Django 4.2.7 on 2024-02-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0030_alter_candidate_level_of_german'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Level_Of_German',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='None', max_length=50, null=True),
        ),
    ]
