# Generated by Django 4.2.7 on 2024-02-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0031_alter_candidate_level_of_german'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='course_intake',
            field=models.CharField(blank=True, choices=[('Class (DEC-AUG 2023/2024 Semester)', 'Class (DEC-AUG 2023/2024 Semester)'), ('Class (JAN-SEPT 2024 Semester)', 'Class (JAN-SEPT 2024 Semester)'), ('Class (FEB-OCT 2024 Semester)', 'Class (FEB-OCT 2024 Semester)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='course_intake',
            field=models.CharField(blank=True, choices=[('Class (DEC-AUG 2023/2024 Semester)', 'Class (DEC-AUG 2023/2024 Semester)'), ('Class (JAN-SEPT 2024 Semester)', 'Class (JAN-SEPT 2024 Semester)'), ('Class (FEB-OCT 2024 Semester)', 'Class (FEB-OCT 2024 Semester)')], max_length=255, null=True),
        ),
    ]
