# Generated by Django 4.2.7 on 2024-02-07 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0032_alter_candidate_course_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
