# Generated by Django 4.2.7 on 2024-01-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0032_remove_attendance_absent_attendance_is_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='crmpage.candidate'),
        ),
    ]
