# Generated by Django 4.2.7 on 2024-02-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0033_feestructure_due_date_feestructure_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='date',
            new_name='starting_date',
        ),
    ]
