# Generated by Django 4.2.7 on 2024-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0033_alter_attendance_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='candidate',
        ),
        migrations.AddField(
            model_name='attendance',
            name='candidates',
            field=models.ManyToManyField(related_name='attendances', to='crmpage.candidate'),
        ),
    ]
