# Generated by Django 4.2.7 on 2024-02-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0036_alter_classfee_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfee',
            name='months_range',
        ),
        migrations.CreateModel(
            name='MonthRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('class_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='crmpage.classfee')),
            ],
        ),
    ]
