# Generated by Django 4.2.7 on 2024-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0037_remove_classfee_months_range_monthrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthrange',
            name='amount_to_pay',
            field=models.IntegerField(default=0),
        ),
    ]
