# Generated by Django 4.2.7 on 2024-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0038_monthrange_amount_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthrange',
            name='amount_to_pay',
            field=models.IntegerField(),
        ),
    ]
