# Generated by Django 4.2.7 on 2024-02-08 20:18

import crmpage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0039_alter_monthrange_amount_to_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount_to_pay', models.IntegerField(default=15000)),
                ('invoice_number', models.CharField(default=crmpage.models.generate_invoice_number, max_length=12)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmpage.candidate')),
            ],
        ),
    ]
