# Generated by Django 4.2.7 on 2024-02-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0041_alter_schoolfee_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
