# Generated by Django 4.2.7 on 2024-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0042_invoice_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('Date_of_Admission', models.DateField()),
                ('German_Level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='None', max_length=50, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='admissions/')),
            ],
        ),
    ]
