# Generated by Django 4.2.7 on 2024-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0043_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='crmpage.candidate'),
        ),
    ]
