# Generated by Django 4.2.7 on 2024-02-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0044_admission_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='candidate',
        ),
    ]
