# Generated by Django 4.2.7 on 2024-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0046_alter_admission_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Course_Location',
            field=models.CharField(choices=[('Nairobi_CBD', 'Nairobi_CBD'), ('Nairobi_Hospital', 'Nairobi_Hospital'), ('Nairobi_Karen', 'Nairobi_Karen'), ('Nairobi_Daystar', 'Nairobi_Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret'), ('Thika', 'Thika')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eldoret_applicant',
            name='Course_Location',
            field=models.CharField(blank=True, choices=[('Nairobi_CBD', 'Nairobi_CBD'), ('Nairobi_Hospital', 'Nairobi_Hospital'), ('Nairobi_Karen', 'Nairobi_Karen'), ('Nairobi_Daystar', 'Nairobi_Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret'), ('Thika', 'Thika')], max_length=50, null=True),
        ),
    ]
