# Generated by Django 4.2.7 on 2024-02-13 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crmpage', '0047_alter_candidate_course_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Starting_Date', models.DateField()),
                ('Ending_Date', models.DateField()),
                ('Amount_to_Pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Invoice_Number', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='Fee_structures/')),
            ],
        ),
    ]
